Add helpers to decode multiple artists/genre (when a file has some)
polyfloyd/rust-id3 pull request #87
Opened 2022-05-25 14:12 UTC by martpie

Fixes https://github.com/polyfloyd/rust-id3/issues/84

I guess this could be added to more tags, up to you. But that's all I need for now.

I'm a rust noob, so don't hesitate to tell me what can be improved in my code.

2022-05-25 17:49 UTC, polyfloyd requested changes

2022-05-25 17:49 UTC, polyfloyd commented on src/tag.rs
> +        fs::copy("testdata/multi-tags.mp3", &tmp).unwrap();
Copying test data is only needed if we write to it. This test only reads, so could you just read from the testdata directly?

2022-05-25 17:49 UTC, polyfloyd commented on src/tag.rs
> +    fn test_multiple_tags() {
Could you rename this to `test_issue_84`? Makes it easier to get some context about what was fixed

2022-05-25 19:26 UTC, polyfloyd requested changes
Could you get rid of that .DS_Store file?

2022-05-25 20:00 UTC, martpie commented
Ah damn macOS 😒

2022-05-26 10:03 UTC, merged

2022-05-26 13:15 UTC, martpie commented
Thank you! FYI, `audiotags` seems not maintained and I may fork it and improve it over time, so it's probably I'll open more issues/PRs in the future 👍